databases:
  - name: anota-ai-db
    plan: free
    databaseName: anota_ai_api
    user: anota_ai_user
    region: oregon

services:
  - type: web
    name: anota-ai-api
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /api/v1/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: anota-ai-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
